catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - .

catalogs:
  cli:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/ni': ^28.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
  deps:
    '@antfu/utils': ^9.3.0
    consola: ^3.4.2
    magic-string: ^0.30.21
    mlly: ^1.8.0
    oxc-transform: ^0.105.0
    unimport: ^5.6.0
    webpack: ^5.104.1
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
