/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unimport-loader
// biome-ignore lint: disable
export {}
declare global {
  const useCallback: typeof import('react').useCallback
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useState: typeof import('react').useState
}
